# This is a basic workflow to help you get started with Actions

name: Release CI

on:
  push:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  

  build-and-release-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2


      - uses: microsoft/setup-msbuild@v1

      - uses: egor-tensin/vs-shell@v2
      
      - name: Set up MSVC environment
        run: vcvarsall.bat x64

      
      - shell: cmd
        run: |
         cl generate.c
    
        
