# This is a basic workflow to help you get started with Actions

name: Release CI

on:
  push:
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  

  build-and-release-windows:
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - uses: microsoft/setup-msbuild@v1.1

      - uses: ilammy/msvc-dev-cmd@v1
    
      - name: Set up MSVC environment
        shell: cmd
        run: |
          "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64

      - shell: cmd
        run: |
          d:
          cd D:\a\stl59\stl59
          dir
          cl generate.c
          generate.exe
          
      - name: Archive Release
        uses: thedoctor0/zip-release@master
        with:
          type: "zip"
          filename: exe-windows.zip
          directory: D:\a\stl59\stl59\msvc

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          path: D:\a\stl59\stl59\msvc
          name: exe-windows.zip
